### ISSUE TITLE
Ability to set multiple local cache directories

### ISSUE THREAD

**Issue by jsta** [esgf2-us/intake-esgf#30]
**Is your feature request related to a problem? Please describe.**
I am using a mounted network drive as a local cache directory because of it's large capacity. However, sometimes this drive is not available.

**Describe the solution you'd like**
I'd like to be able to specify multiple cache directories to split my cache among a-couple/several different drives.

**Comment by nocollier** [comment]
This should not be a problem and pretty reasonable. A couple of thoughts come to mind:

* Perhaps we need to remove the `esg_data_root` and expand `local_cache` to have variable number of locations. I could simply check for institutional access and add it in as a cache instead of a separate variable.
* A local cache would then need to have a notion of 'readonly' so we never try to download files to certain locations. You might want some of your drives write protected.
* We also need a way to flag which cache to download to for the current session.

At some point I need a better configure setup so a user can see all the assumptions.
