### ISSUE TITLE
Including extra metadata from search results into the dataframe

### ISSUE THREAD

**Issue by huard** [esgf2-us/intake-esgf#52]
**Is your feature request related to a problem? Please describe.**

I want to filter simulations based on the time period. More specifically, I want to build a catalog of simulations available post 2100 and understand what kind of data coverage I'll get in terms of experiment_ids, source_ids, variables, etc.

**Describe the solution you'd like**

The esgf-search API supports temporal search using the `start` and `end` search parameters. See https://esgf.github.io/esg-search/ESGF_Search_RESTful_API.html#temporal-coverage-queries

Example query: 
```
https://esgf-node.llnl.gov/esg-search/search?cf_standard_name=air_temperature&activity_id=ScenarioMIP&start=2101-01-02T00:00:00Z
```

I can pass `start` and `end` params to `ESGFCatalog().search` provided I enable at least one `SolrESGFIndex` node. However, the resulting DataFrame does not include the `datetime_start` and `datetime_stop` information, which are necessary to estimate how many years of simulations are available. 

The facet extraction logic is in `get_dataframe_columns`, which cannot be easily modified by subclassing the SolrESGFIndex class. 

A solution to this specific problem would be to add `datetime_start` and `datetime_end` to facets extracted from the response if search params include `start` or `end`. 

A more generic solution would be give the user some manual control over extracted facets.

**Describe alternatives you've considered**

Another option would be to save the full search response document within the ESGFCatalog instance, over which user-defined functions could operate.

**Comment by nocollier** [comment]
Thanks for this suggestion David. I am struggling to organize my thoughts and so here is a bit of a stream of consciousness:

For no particular reason, I included as dataframe columns the facets ESGF uses to uniquely define datasets. This is of course an artificial limitation. It isn't a big deal to include other columns by default--I just need to think about how to handle other projects that may not have those data in their records. 

I would propose that we keep a configuration variable `additional_df_cols` which is a list of other metadata to extract from the response and include in the pandas dataframe. I would add the below in as defaults, but then the user could also set whatever else they want:

```python
intake_esgf.conf.set(additional_df_cols=["datetime_start","datetime_end"])
```

Then I can remove any dataframe column that is all `NaN`/empty so it doesn't pollute the interface if the project does not contain that metadata in the records. Does that feel like a natural way to interact with the functionality?

However, I am not sure that what you propose to do will work because as I understand the records were not ingested to reflect proper datetime ranges. See this list of `datetime_end` facet values:

https://esgf-node.llnl.gov/esg-search/search?limit=0&facets=datetime_end

Unless I have misunderstood something, you will see that the latest entry is in the 1970's. Frankly, it is embarrassing to see the index in such a state. The good news is that, unofficially, ESGF is moving to [STAC](https://stacspec.org/en). We had a meeting last week about this and it means the whole index needs re-ingested. Personally I will scream and yell for this to get fixed.

**Comment by huard** [comment]
I think your proposed solution makes sense. I would maybe add some way to show the list of available facets, so users have a sense of what they can ask for, and debug typos. 

I'm confident it will ! You're just looking at the first "page" of facets, the full list has 15383515 entries.

**Comment by nocollier** [comment]
Ah yes, there must be some limit to the facets that it will return, when I add an `activity_id` I see later dates:

https://esgf-node.llnl.gov/esg-search/search?type=Dataset&limit=0&activity_id=ScenarioMIP&facets=datetime_end

I can also make the Globus indices behave in the same way. They contain the same information, it is just that I didn't special case the `datetime_XXX` search facets to behave as the ESGF REST API. So it is looking at `==` implicitly instead of `>=`, etc..

I have a bit of a queue at the moment and need to catch up on other projects, but will get to this as soon as I can.

**Comment by nocollier** [comment]
Added in #54
