### ISSUE TITLE
Asymmetry between ESGF offerings and intake-esgf search results

### ISSUE THREAD

**Issue by alexkjames** [esgf2-us/intake-esgf#74]
**Description:**

There seems to be an asymmetry in the availability of data provided by intake-esgf and the ESGF Metagrid website. In my case, I was able to locate [ACCESS-ESM1-5 runs for the past1000 experiment from PMIP on Metagrid](https://aims2.llnl.gov/search?project=CMIP6&activeFacets=%7B%22experiment_id%22%3A%22past1000%22%2C%22source_id%22%3A%22ACCESS-ESM1-5%22%7D) (and download them via wget), but intake-esgf returns an empty search when I look for this combination of source id and experiment id. This appears to only be the case for ACCESS-ESM1-5, as the other models I expect to be available from the past1000 experiment (INM-CM4-8, MIROC-ES2L, and MRI-ESM2-0), are findable via intake-esgf.

**Version:** 2024.10.25

**Example:**

```
from intake_esgf import ESGFCatalog
cat = ESGFCatalog()

search_result = cat.search(
    experiment_id='past1000',
    source_id='ACCESS-ESM1-5'
)
```

**Comment by nocollier** [comment]
Hey Alex! Thanks for writing.

In short, `intake-esgf` is configured to, by default, use Globus/ElasticSearch-based indices we are developing which contain a lot of the global ESGF holdings but not all of them. We provide backward compatibility to the old Solr-based nodes which Metagrid is using. You just need to configure intake-esgf to use them:

```python
import intake_esgf
intake_esgf.conf.set(all_indices=True)
cat = intake_esgf.ESGFCatalog()
cat.search(experiment_id="past1000")
```

I don't use them by default because they are slow and flaky. When I ran this, I had a number of index nodes fail:

```bash
   Searching indices:   0%|                                                        |0/9 [       ?
index/s]/home/nate/miniconda3/lib/python3.12/site-packages/intake_esgf/catalog.py:268: UserWarning: SolrESGFIndex('esgf-data.dkrz.de') failed to return a response, results may be incomplete
  warnings.warn(
   Searching indices:  11%|██████▏                                                 |1/9 [    
6.97index/s]/home/nate/miniconda3/lib/python3.12/site-packages/intake_esgf/catalog.py:268: UserWarning: SolrESGFIndex('esgf-node.llnl.gov') failed to return a response, results may be incomplete
  warnings.warn(
/home/nate/miniconda3/lib/python3.12/site-packages/intake_esgf/catalog.py:268: UserWarning: SolrESGFIndex('esgf.nci.org.au') failed to return a response, results may be incomplete
  warnings.warn(
   Searching indices: 100%|████████████████████████████████████████████████████████|9/9 [    4.00s/index]
Out[5]: 
Summary information for 813 results:
mip_era                                                     [CMIP6]
activity_drs                                                 [PMIP]
institution_id                                    [MIROC, MRI, INM]
source_id                       [MIROC-ES2L, MRI-ESM2-0, INM-CM4-8]
experiment_id                                            [past1000]
member_id                                      [r1i1p1f2, r1i1p1f1]
table_id          [Amon, Lmon, Omon, fx, LImon, Emon, CFmon, SIm...
variable_id       [tas, nbp, fgco2, sftlf, po4os, friver, frn, t...
grid_label                             [gn, gr1, gnz, gr, gr2z, gm]
dtype: object
```

I presume that the ACCESS model results are on the Austrailian index node which for me just failed. At least intake-esgf tells you the index node failed to return a response.

This is a situation that the global ESGF federation is working to resolve even as we speak/type. The situation should be better in time for CMIP7 fast track and in the meantime, you may need to use these Solr-based indices even though they are increasingly unreliable.

**Comment by alexkjames** [comment]
I see, thank you so much for this explanation! This is super helpful, I'll give the old nodes a shot.
